# Generated by Django 3.2.4 on 2021-06-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='publicUrl',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
